name: del
on:
  push:
    branches: [ main ]
    paths:
      - del_*
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: echo ${{steps.files.outputs.added}}
    outputs:
      matrix: ${{ steps.files.outputs.added }}

  job2:
    needs: job1
    if: needs.job1.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        added-file: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo "${{matrix.added-file}}"

  job3:
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.job1.outputs.matrix}}
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: |
          readarray -t myfiles <<<"$(jq -r '.[]' <<<'${{ needs.job1.outputs.matrix }}')"
          for myfile in ${myfiles[@]}; do
            git rm '${myfile}'
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
      
      # - run: git commit -m "removed file ${{ matrix.added-file }}"
      # - run: git pull --tags origin main
      # # git pull
      # - run: git push --force
