name: smtp
on:
  push:
    branches: [ main ]
    paths:
      - del*
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: echo ${{steps.files.outputs.added}}
    outputs:
      matrix: ${{ steps.files.outputs.added }}

  job2:
    needs: job1
    if: needs.job1.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        added-file: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{matrix.added-file}}
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: |
          git rm --cached '${{matrix.added-file}}'
          git commit -m 'remove ${{ matrix.added-file }}'
          git push
  