name: del
on:
  push:
    branches: [ main ]
    paths:
      - del_*
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files-csv
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - id: files-json
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: echo ${{steps.files.outputs.added}}
    outputs:
      json: ${{ steps.files-json.outputs.added }}
      csv: ${{ steps.files-csv.outputs.added }}

  job2:
    needs: job1
    if: needs.job1.outputs.json != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        added-file: ${{fromJson(needs.job1.outputs.json)}}
    steps:
      - run: echo "${{matrix.added-file}}"

  job3:
    needs: [job1,job2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      - run: git rm ${{needs.job1.outputs.csv}}
      - uses: stefanzweifel/git-auto-commit-action@v4