name: smtp
on:
  push:
    branches: [ main ]
    paths:
      - move/smtp*
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process-smtp:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          echo ${{ steps.files.outputs.added }}

      - uses: haya14busa/action-cond@v1
        id: filesadded
        with:
          cond: ${{ steps.files.outputs.added != '' }}
          if_true: 1
          if_false: 0

      - name: Send mail
        if: steps.filesadded.outputs.if_true == 1
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: royashbrook@me.com
          from: GitMFT # <user@example.com>
          body: Files added - ${{ steps.files.outputs.added }}
          attachments: ${{ steps.files.outputs.added }}

      - name: Remove File
        if: steps.filesadded.outputs.if_true == 1
        uses: JesseTG/rm@v1.0.2
        with:
          path: steps.files.outputs.added

      - name: Push changes
        if: steps.filesadded.outputs.if_true == 1
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}