name: smtp
on:
  push:
    branches: [ main ]
    paths:
      - move/smtp*
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  process-smtp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          echo ${{ steps.files.outputs.added }}

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: royashbrook@me.com
          from: GitMFT # <user@example.com>
          body: Files added - ${{ steps.files.outputs.added }}
          attachments: ${{ steps.files.outputs.added }}

